feat: compare local git name with project owner name
Determines if git clone should happen over ssh or https

diff --git a/pctl b/pctl
--- a/pctl
+++ b/pctl
@@ -173,14 +173,26 @@ get_project() {
 
     local project_name="${project##*/}"
     local project_dir="${project%/*}"
-    local gh_repo_owner=$(awk -F, -v selected="$project" '$1 == selected {print $2}' "$PROJECTLIST")
 
     if [[ ! -d $project_dir ]]; then
         mkdir -p "$project_dir"
     fi
 
-    echo -en "Cloning ${BLUE}$project_name${RESET} "
-    git clone --quiet git@github.com:"$gh_repo_owner/$project_name" "$project" > /dev/null
+    # Get repo owner name, compare it to local git name to know if use ssh or https clone
+    # NOTE: maybe better to add the --dev=false flag
+    local gh_repo_owner=$(awk -F, -v selected="$project" '$1 == selected {print $2}' "$PROJECTLIST")
+    local gh_repo_owner_name=$(curl -s https://api.github.com/users/"$gh_repo_owner" | awk -F'"' '/"name":/ {print $4}')
+    local local_gitconf_name=$(git config --global --list | awk -F= -v selected="user.name" '$1 == selected {print $2}')
+
+    local gh_clone_url="git@github.com:"
+
+    if [[ "$gh_repo_owner_name" != "$local_gitconf_name" ]]; then
+        gh_clone_url="https://github.com/"
+    fi
+
+    echo -e "Cloning ${BLUE}$project_name${RESET} "
+    echo "Woud git clone --quiet \"$gh_clone_url$gh_repo_owner/$project_name\" \"$project\" > /dev/null"
+    # git clone --quiet "$gh_clone_url$gh_repo_owner/$project_name" "$project" > /dev/null
     # INFO: requires a Nerd Font
     echo -e "${GREEN}󰄴${RESET}"
 }
@@ -254,6 +266,16 @@ EOF
 main() {
     ensure_installed fzf
     ensure_installed tmux
+
+    # Check if git config name and email are configured
+    if ! git config --global --list > /dev/null; then
+        echo "Error: git not configured."
+        echo "Run:"
+        echo "  git config --global user.name \"<Your Name\""
+        echo "and"
+        echo "  git config --global user.email \"<Your Email\""
+        exit 1
+    fi
 
     readonly CURRENT_USER=$(whoami)
     readonly PCTL_SHARE="$HOME/.local/share/pctl"
